// == AUTH ACTIONS
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const REMOVE_CURRENT_USER = "REMOVE_CURRENT_USER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const AUTH_LOADING = "AUTH_LOADING";
export const RESET_AUTH_STATE = "RESET_AUTH_STATE";
export const GET_ERROR = "GET_ERROR";

// == USER/PROFILE ACTIONS
export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILES = "GET_PROFILES";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";
export const PROFILES_LOADING = "PROFILES_LOADING";
export const GET_PROFILE_ERROR = "GET_PROFILE_ERROR";

// == MOVIE ACTIONS
export const GET_MOVIES = "GET_MOVIES";
export const GET_MOVIE = "GET_MOVIE";
export const GET_POPULAR_MOVIES = "GET_POPULAR_MOVIES";
export const POST_MOVIE_SUCCESS = "POST_MOVIE_SUCCESS";
export const POST_MOVIE_FAIL = "POST_MOVIE_FAIL";
export const UPDATE_MOVIE_SUCCESS = "UPDATE_MOVIE_SUCCESS";
export const UPDATE_MOVIE_FAIL = "UPDATE_MOVIE_FAIL";
export const MOVIES_LOADING = "MOVIES_LOADING";
export const GET_MOVIES_ERROR = "GET_MOVIES_ERROR";

// == CONTRIBUTION ACTIONS
export const GET_CONTRIBUTION = "GET_CONTRIBUTION";
export const GET_CONTRIBUTIONS = "GET_CONTRIBUTIONS";
export const CREATE_CONTRIBUTION_SUCCESS = "CREATE_CONTRIBUTION_SUCCESS";
export const CREATE_CONTRIBUTION_FAIL = "CREATE_CONTRIBUTION_FAIL";
export const UPDATE_CONTRIBUTION_SUCCESS = "UPDATE_CONTRIBUTION_SUCCESS";
export const UPDATE_CONTRIBUTION_FAIL = "UPDATE_CONTRIBUTION_FAIL";
export const DELETE_CONTRIBUTION_SUCCESS = "DELETE_CONTRIBUTION_SUCCESS";
export const DELETE_CONTRIBUTION_FAIL = "DELETE_CONTRIBUTION_FAIL";
export const CONTRIBUTIONS_LOADING = "CONTRIBUTIONS_LOADING";
export const GET_CONTRIBUTIONS_ERROR = "GET_CONTRIBUTIONS_ERROR";

// == PEOPLE ACTIONS
export const GET_PERSON = "GET_PERSON";
export const GET_PEOPLE = "GET_PEOPLE";
export const CREATE_PERSON_SUCCESS = "CREATE_PERSON_SUCCESS";
export const CREATE_PERSON_FAIL = "CREATE_PERSON_FAIL";
export const UPDATE_PERSON_SUCCESS = "UPDATE_PERSON_SUCCESS";
export const UPDATE_PERSON_FAIL = "UPDATE_PERSON_FAIL";
export const DELETE_PERSON_SUCCESS = "DELETE_PERSON_SUCCESS";
export const DELETE_PERSON_FAIL = "DELETE_PERSON_FAIL";
export const PEOPLE_LOADING = "PEOPLE_LOADING";
export const GET_PEOPLE_ERROR = "GET_PEOPLE_ERROR";
