// == AUTH ACTIONS
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const REMOVE_CURRENT_USER = "REMOVE_CURRENT_USER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const AUTH_LOADING = "AUTH_LOADING";
export const RESET_AUTH_STATE = "RESET_AUTH_STATE";
export const GET_ERROR = "GET_ERROR";

// == USER/PROFILE ACTIONS
export const GET_PROFILE = "GET_PROFILE";
export const GET_CURRENT_PROFILE = "GET_CURRENT_PROFILE";
export const GET_PROFILES = "GET_PROFILES";
export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAIL = "UPDATE_PROFILE_FAIL";
export const PROFILES_LOADING = "PROFILES_LOADING";
export const GET_PROFILE_ERROR = "GET_PROFILE_ERROR";

// == MOVIE ACTIONS
export const GET_MOVIES = "GET_MOVIES";
export const SEARCH_MOVIES = "SEARCH_MOVIES";
export const GET_MOVIE = "GET_MOVIE";
export const GET_POPULAR_MOVIES = "GET_POPULAR_MOVIES";
export const CREATE_MOVIE_SUCCESS = "CREATE_MOVIE_SUCCESS";
export const CREATE_MOVIE_FAIL = "CREATE_MOVIE_FAIL";
export const UPDATE_MOVIE_SUCCESS = "UPDATE_MOVIE_SUCCESS";
export const UPDATE_MOVIE_FAIL = "UPDATE_MOVIE_FAIL";
export const MOVIES_LOADING = "MOVIES_LOADING";
export const GET_MOVIES_ERROR = "GET_MOVIES_ERROR";

// == CONTRIBUTION ACTIONS
export const GET_CONTRIBUTION = "GET_CONTRIBUTION";
export const GET_CONTRIBUTIONS = "GET_CONTRIBUTIONS";
export const CREATE_CONTRIBUTION_SUCCESS = "CREATE_CONTRIBUTION_SUCCESS";
export const CREATE_CONTRIBUTION_FAIL = "CREATE_CONTRIBUTION_FAIL";
export const UPDATE_CONTRIBUTION_SUCCESS = "UPDATE_CONTRIBUTION_SUCCESS";
export const UPDATE_CONTRIBUTION_FAIL = "UPDATE_CONTRIBUTION_FAIL";
export const DELETE_CONTRIBUTION_SUCCESS = "DELETE_CONTRIBUTION_SUCCESS";
export const DELETE_CONTRIBUTION_FAIL = "DELETE_CONTRIBUTION_FAIL";
export const CONTRIBUTIONS_LOADING = "CONTRIBUTIONS_LOADING";
export const GET_CONTRIBUTIONS_ERROR = "GET_CONTRIBUTIONS_ERROR";

// == PEOPLE ACTIONS
export const GET_PERSON = "GET_PERSON";
export const GET_PEOPLE = "GET_PEOPLE";
export const CREATE_PERSON_SUCCESS = "CREATE_PERSON_SUCCESS";
export const CREATE_PERSON_FAIL = "CREATE_PERSON_FAIL";
export const UPDATE_PERSON_SUCCESS = "UPDATE_PERSON_SUCCESS";
export const UPDATE_PERSON_FAIL = "UPDATE_PERSON_FAIL";
export const DELETE_PERSON_SUCCESS = "DELETE_PERSON_SUCCESS";
export const DELETE_PERSON_FAIL = "DELETE_PERSON_FAIL";
export const PEOPLE_LOADING = "PEOPLE_LOADING";
export const GET_PEOPLE_ERROR = "GET_PEOPLE_ERROR";

// == PEOPLE CONNECTION ACTIONS
export const GET_PEOPLE_CONNECTIONS = "GET_PEOPLE_CONNECTIONS";
export const FOLLOW_PERSON_SUCCESS = "FOLLOW_PERSON_SUCCESS";
export const FOLLOW_PERSON_FAIL = "FOLLOW_PERSON_FAIL";
export const UNFOLLOW_PERSON_SUCCESS = "UNFOLLOW_PERSON_SUCCESS";
export const UNFOLLOW_PERSON_FAIL = "UNFOLLOW_PERSON_FAIL";
export const PEOPLE_CONNECTIONS_LOADING = "PEOPLE_CONNECTIONS_LOADING";
export const GET_PEOPLE_CONNECTION_ERROR = "GET_PEOPLE_CONNECTION_ERROR";

// == USER CONNECTION ACTIONS
export const GET_FOLLOWERS = "GET_FOLLOWERS";
export const GET_FOLLOWING = "GET_FOLLOWING";
export const FOLLOW_USER_SUCCESS = "FOLLOW_USER_SUCCESS";
export const FOLLOW_USER_FAIL = "FOLLOW_USER_FAIL";
export const UNFOLLOW_USER_SUCCESS = "UNFOLLOW_USER_SUCCESS";
export const UNFOLLOW_USER_FAIL = "UNFOLLOW_USER_FAIL";
export const USERS_CONNECTIONS_LOADING = "USER_CONNECTIONS_LOADING";

// == REVIEW ACTIONS
export const GET_MOVIE_REVIEWS = "GET_MOVIE_REVIEWS";
export const GET_REVIEW = "GET_REVIEW";
export const CREATE_REVIEW_SUCCESS = "CREATE_REVIEW_SUCCESS";
export const CREATE_REVIEW_FAIL = "CREATE_REVIEW_FAIL";
export const REVIEWS_LOADING = "REVIEWS_LOADING";

// == SOCKETS ACTIONS
export const ADD_SOCKET_REF = "ADD_SOCKET_REF";
